[platformio]
default_envs = PaperS3

[env:PaperS3]
platform = espressif32@6.12.0
board = esp32-s3-devkitm-1
framework = espidf

upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions.csv

extra_scripts =
  pre:tools/gen_builtin_ui_font.py

lib_ignore =
  M5Unified
  M5GFX

build_flags =
  -std=gnu++17
  -O2
  -Wno-error
  -Wno-unused-function
  -Wno-deprecated-declarations
  -DCONFIG_EPD_DISPLAY_TYPE_ED047TC2
  -DCONFIG_EPD_BOARD_REVISION_LILYGO_T5_47
  -DPS3_FONT_WIDTH=24
  -DPS3_FONT_HEIGHT=24
  -UARDUINO_ESP32S3_DEV
  -UARDUINO_ARCH_ESP32

build_unflags =
  -std=gnu++11
