// AUTO-GENERATED by scripts/gen_builtin_ui_font.py - do not edit.
// Source TTFs:
//   BIZ UDGothic Regular: BIZUDGothic-Regular.ttf
//   IPAex Gothic:         ipaexg.ttf
// Subset: ASCII + Latin-1 + CJK Punct + Hiragana + Katakana +
//         Halfwidth/Fullwidth + JIS X 0208 Level 1 kanji
// Glyph cell: 24 x 24 px (72 bytes/glyph)
// Glyph count: 3651  (~256 KiB per face)

#pragma once

#include <cstdint>

namespace ps3::font {

inline constexpr int kBuiltinUiFontW              = 24;
inline constexpr int kBuiltinUiFontH              = 24;
inline constexpr int kBuiltinUiFontGlyphCount     = 3651;
inline constexpr int kBuiltinUiFontBytesPerGlyph  = 72;

extern const uint16_t kBuiltinUiFontCodepoints[kBuiltinUiFontGlyphCount];
extern const uint8_t  kBuiltinUiFontGlyphs[kBuiltinUiFontGlyphCount
                                            * kBuiltinUiFontBytesPerGlyph];
extern const uint8_t  kBuiltinIpaGothicGlyphs[kBuiltinUiFontGlyphCount
                                               * kBuiltinUiFontBytesPerGlyph];

}  // namespace ps3::font

// fingerprint: 496879de95b44282
