// AUTO-GENERATED by tools/font_candidates.py --emit-firmware - do not edit.
// fingerprint: 3afe44c129cac35c

#pragma once

#include <cstdint>

namespace ps3::font {

inline constexpr int kFontLabGlyphW = 24;
inline constexpr int kFontLabGlyphH = 24;
inline constexpr int kFontLabGlyphCount = 165;
inline constexpr int kFontLabBytesPerGlyph = 72;

struct FontLabFace {
    const char* key;
    const char* display_name;
    const char* source;
    const char* weight;
    const char* license;
    const uint8_t* glyphs;
};

extern const uint16_t kFontLabCodepoints[kFontLabGlyphCount];
extern const FontLabFace kFontLabFaces[];
extern const int kFontLabFaceCount;

}  // namespace ps3::font
