#!/usr/bin/env python3
"""Generate the built-in UI font header from a TTF.

PIO pre-build hook (also runnable standalone). Rasterises a subset of
glyphs (JIS X 0208 Level 1 kanji + ASCII / Latin-1 / kana / CJK
punctuation / halfwidth-fullwidth forms) from the supplied TTF at the
build's PS3_FONT_WIDTH x PS3_FONT_HEIGHT and writes
src/font/builtin_ui_font.{h,cpp} as XTEinkFont::bind_sparse-ready
arrays.

The output is a sparse codepoint+glyph pair: a sorted uint16_t table
of supported codepoints and a parallel byte array of glyph bitmaps in
the same MSB-first packed format as the SD-loaded XTEink .bin
(`ceil(W/8) * H` bytes per glyph). XTEinkFont::pixel() does a binary
search on the codepoint table; ~12 comparisons for the ~3500-glyph
subset is negligible vs. the framebuffer write costs.

Re-runs only when inputs (TTF mtime + dimensions + codepoint set
fingerprint) change, so PIO's incremental rebuild path stays clean.
"""

import hashlib
import os
import sys
from pathlib import Path

# PIO context detection. When invoked as `pre:` extra_script PIO injects
# `Import` and `env` globals; when run standalone they don't exist and
# we drop into `main_standalone()` at the bottom.
try:
    Import("env")  # type: ignore[name-defined]  # noqa: F821
    _IN_PIO = True
except NameError:
    _IN_PIO = False


# ---------------------------------------------------------------------------
# Codepoint set
# ---------------------------------------------------------------------------

def _enumerate_jis_l1_kanji():
    """Yield Unicode codepoints for JIS X 0208 Level 1 kanji.

    Level 1 occupies rows 16-47 in JIS encoding. We iterate via EUC-JP
    (which is just JIS + 0x80) and decode each cell to its Unicode
    equivalent — this avoids vendoring a JIS-Unicode mapping table and
    relies only on Python's built-in codec.
    """
    for row in range(16, 48):
        for col in range(1, 95):
            euc = bytes([row + 0xA0, col + 0xA0])
            try:
                ch = euc.decode("euc_jp")
            except UnicodeDecodeError:
                continue
            if len(ch) == 1 and ord(ch) > 0x3000 and ord(ch) <= 0xFFFD:
                yield ord(ch)


def build_codepoint_set():
    """Return sorted list of codepoints to bake into the firmware.

    Coverage (~3500 codepoints):
      - ASCII printable                   (0x0020..0x007E)
      - Latin-1 supplement                 (0x00A0..0x00FF)
      - CJK Symbols and Punctuation        (0x3000..0x303F)
      - Hiragana                           (0x3041..0x309F)
      - Katakana                           (0x30A0..0x30FF)
      - Halfwidth and Fullwidth Forms      (0xFF00..0xFFEF)
      - JIS X 0208 Level 1 kanji           (~2,965 codepoints)
    """
    cps = set()
    cps.update(range(0x0020, 0x007F))
    cps.update(range(0x00A0, 0x0100))
    cps.update(range(0x3000, 0x3040))
    cps.update(range(0x3041, 0x30A0))
    cps.update(range(0x30A0, 0x3100))
    cps.update(range(0xFF00, 0xFFF0))
    for cp in _enumerate_jis_l1_kanji():
        cps.add(cp)
    return sorted(cps)


# ---------------------------------------------------------------------------
# Rasterisation
# ---------------------------------------------------------------------------

def _rasterise_glyph(font, ch, width, height, baseline_y):
    """Render `ch` into an `width x height` 1-bit bitmap.

    Uses an L-mode (8-bit grayscale) intermediate so anti-aliased edges
    can be thresholded into the cleanest 1-bit shape — direct mode='1'
    text rendering tends to leave broken strokes at small sizes.
    """
    from PIL import Image, ImageDraw

    img = Image.new("L", (width, height), color=0)
    draw = ImageDraw.Draw(img)
    # Anchor 'la' (left-ascender) places (x, y) at the left edge / top
    # of the ascent. We position glyph horizontally near the left,
    # leaving the font itself (proportional) to set the actual width;
    # XTEinkFont fills 0xF in the unused right margin so monospaced
    # rendering stays clean.
    draw.text((0, 0), ch, font=font, fill=255, anchor="la")

    width_byte = (width + 7) // 8
    out = bytearray(width_byte * height)
    px = img.load()
    for y in range(height):
        for x in range(width):
            if px[x, y] >= 128:
                out[y * width_byte + (x >> 3)] |= 0x80 >> (x & 7)
    return bytes(out)


# ---------------------------------------------------------------------------
# Header / source emission
# ---------------------------------------------------------------------------

_HEADER_TEMPLATE = """// AUTO-GENERATED by scripts/gen_builtin_ui_font.py - do not edit.
// Source TTFs:
//   BIZ UDGothic Regular: {biz_ttf_name}
//   IPAex Gothic:         {ipa_ttf_name}
// Subset: ASCII + Latin-1 + CJK Punct + Hiragana + Katakana +
//         Halfwidth/Fullwidth + JIS X 0208 Level 1 kanji
// Glyph cell: {w} x {h} px ({char_byte} bytes/glyph)
// Glyph count: {count}  (~{kib} KiB per face)

#pragma once

#include <cstdint>

namespace ps3::font {{

inline constexpr int kBuiltinUiFontW              = {w};
inline constexpr int kBuiltinUiFontH              = {h};
inline constexpr int kBuiltinUiFontGlyphCount     = {count};
inline constexpr int kBuiltinUiFontBytesPerGlyph  = {char_byte};

extern const uint16_t kBuiltinUiFontCodepoints[kBuiltinUiFontGlyphCount];
extern const uint8_t  kBuiltinUiFontGlyphs[kBuiltinUiFontGlyphCount
                                            * kBuiltinUiFontBytesPerGlyph];
extern const uint8_t  kBuiltinIpaGothicGlyphs[kBuiltinUiFontGlyphCount
                                               * kBuiltinUiFontBytesPerGlyph];

}}  // namespace ps3::font
"""


def _emit_header(out_path, biz_ttf_path, ipa_ttf_path, width, height, char_byte, count):
    out_path.write_text(
        _HEADER_TEMPLATE.format(
            biz_ttf_name=biz_ttf_path.name,
            ipa_ttf_name=ipa_ttf_path.name,
            w=width,
            h=height,
            char_byte=char_byte,
            count=count,
            kib=count * char_byte // 1024,
        ),
        encoding="utf-8",
    )


def _emit_source(out_path, codepoints, face_blobs):
    lines = [
        "// AUTO-GENERATED by scripts/gen_builtin_ui_font.py - do not edit.",
        "",
        '#include "builtin_ui_font.h"',
        "",
        "namespace ps3::font {",
        "",
        "const uint16_t kBuiltinUiFontCodepoints[kBuiltinUiFontGlyphCount] = {",
    ]
    chunk = []
    for i, cp in enumerate(codepoints):
        chunk.append(f"0x{cp:04X}")
        if (i + 1) % 12 == 0 or i == len(codepoints) - 1:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    lines.append("};")
    lines.append("")
    for symbol, glyph_blob in face_blobs:
        lines.append(f"const uint8_t {symbol}[kBuiltinUiFontGlyphCount")
        lines.append("                                  * kBuiltinUiFontBytesPerGlyph] = {")
        chunk = []
        for i, b in enumerate(glyph_blob):
            chunk.append(f"0x{b:02X}")
            if (i + 1) % 16 == 0 or i == len(glyph_blob) - 1:
                lines.append("    " + ", ".join(chunk) + ",")
                chunk = []
        lines.append("};")
        lines.append("")
    lines.append("}  // namespace ps3::font")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def _fingerprint(ttf_paths, width, height, codepoints):
    """Hash of inputs, used to skip regeneration when nothing changed."""
    h = hashlib.sha256()
    h.update(f"{width}x{height}\n".encode())
    h.update(b"\x00".join(f"{cp:x}".encode() for cp in codepoints))
    h.update(b"\x00")
    for ttf_path in ttf_paths:
        h.update(str(ttf_path).encode())
        h.update(str(ttf_path.stat().st_mtime_ns).encode())
        h.update(str(ttf_path.stat().st_size).encode())
    return h.hexdigest()[:16]


def generate(font_specs, header_path, source_path, width, height):
    try:
        from PIL import ImageFont
    except ImportError:
        print(
            "!! gen_builtin_ui_font: Pillow not installed. "
            "Run `~/.platformio/penv/Scripts/pip install pillow`.",
            file=sys.stderr,
        )
        return False

    codepoints = build_codepoint_set()
    ttf_paths = [spec[1] for spec in font_specs]
    fp = _fingerprint(ttf_paths, width, height, codepoints)
    fp_marker = "// fingerprint: " + fp
    if header_path.exists() and source_path.exists():
        head = header_path.read_text(encoding="utf-8", errors="replace")
        if fp_marker in head:
            return True

    char_byte = ((width + 7) // 8) * height
    face_blobs = []
    for symbol, ttf_path in font_specs:
        font = ImageFont.truetype(str(ttf_path), size=height)
        # Pillow returns metrics that may push the rendered glyph past `height`
        # pixels for fonts with generous descent. We center the cell using the
        # font's ascent so kanji with descenders don't get clipped at the top.
        ascent, _descent = font.getmetrics()
        baseline_y = max(0, ascent - 1)
        blob = bytearray()
        missing = 0
        for cp in codepoints:
            try:
                blob.extend(_rasterise_glyph(font, chr(cp), width, height, baseline_y))
            except (OSError, ValueError):
                blob.extend(bytes(char_byte))
                missing += 1
        face_blobs.append((symbol, blob, missing, ttf_path))

    # Header gets a fingerprint comment so subsequent runs can short-circuit.
    header_text = _HEADER_TEMPLATE.format(
        biz_ttf_name=font_specs[0][1].name,
        ipa_ttf_name=font_specs[1][1].name,
        w=width,
        h=height,
        char_byte=char_byte,
        count=len(codepoints),
        kib=len(codepoints) * char_byte // 1024,
    ).rstrip("\n") + "\n\n" + fp_marker + "\n"
    header_path.write_text(header_text, encoding="utf-8")
    _emit_source(source_path, codepoints, [(symbol, blob) for symbol, blob, _missing, _ttf in face_blobs])
    details = ", ".join(
        f"{ttf_path.name}: {len(blob) // 1024} KiB" + (f" ({missing} missing)" if missing else "")
        for _symbol, blob, missing, ttf_path in face_blobs
    )
    print(
        f">> gen_builtin_ui_font: {header_path.name} + {source_path.name} "
        f"({len(codepoints)} glyphs; {details})"
    )
    return True


def _font_dim_from_env(env, key, default):
    for flag in env.get("BUILD_FLAGS", []) or []:
        if isinstance(flag, str) and flag.startswith(f"-D{key}="):
            try:
                return int(flag.split("=", 1)[1])
            except ValueError:
                pass
    return default


def main_pio():
    env = globals()["env"]
    project_dir = Path(env.subst("$PROJECT_DIR"))
    biz_ttf = project_dir / "assets" / "fonts" / "source" / "BIZUDGothic-Regular.ttf"
    ipa_ttf = project_dir / "assets" / "fonts" / "source" / "ipaexg.ttf"
    header = project_dir / "src" / "font" / "builtin_ui_font.h"
    source = project_dir / "src" / "font" / "builtin_ui_font.cpp"
    width = _font_dim_from_env(env, "PS3_FONT_WIDTH", 24)
    height = _font_dim_from_env(env, "PS3_FONT_HEIGHT", 24)

    missing = [str(path) for path in (biz_ttf, ipa_ttf) if not path.exists()]
    if missing:
        print(
            f"!! gen_builtin_ui_font: TTF missing at {', '.join(missing)}, "
            "firmware will boot without a built-in UI font fallback.",
            file=sys.stderr,
        )
        return
    generate(
        [
            ("kBuiltinUiFontGlyphs", biz_ttf),
            ("kBuiltinIpaGothicGlyphs", ipa_ttf),
        ],
        header,
        source,
        width,
        height,
    )


def main_standalone():
    here = Path(__file__).resolve().parent
    project_dir = here.parent
    biz_ttf = project_dir / "assets" / "fonts" / "source" / "BIZUDGothic-Regular.ttf"
    ipa_ttf = project_dir / "assets" / "fonts" / "source" / "ipaexg.ttf"
    header = project_dir / "src" / "font" / "builtin_ui_font.h"
    source = project_dir / "src" / "font" / "builtin_ui_font.cpp"
    missing = [str(path) for path in (biz_ttf, ipa_ttf) if not path.exists()]
    if missing:
        print(f"TTF not found: {', '.join(missing)}", file=sys.stderr)
        sys.exit(1)
    width = int(os.environ.get("PS3_FONT_WIDTH", 24))
    height = int(os.environ.get("PS3_FONT_HEIGHT", 24))
    if not generate(
        [
            ("kBuiltinUiFontGlyphs", biz_ttf),
            ("kBuiltinIpaGothicGlyphs", ipa_ttf),
        ],
        header,
        source,
        width,
        height,
    ):
        sys.exit(1)


if _IN_PIO:
    main_pio()
elif __name__ == "__main__":
    main_standalone()
