"""Pre-build hook: convert assets/icons/**/*.png into 4 bpp packed icon
arrays embedded in src/library/icons_data.hpp.

Two icon sets:
  - Menu icons (assets/icons/*.png)        -> ICON_GOUP, ICON_PAGEPREV,
                                              ICON_PAGENEXT, ICON_THUMBNAIL
  - Toolbar icons (assets/icons/toolbar/)  -> ICON_TOOLBAR_SLEEP

Each slot can render either a bitmap icon (when its PNG is present) or
a text label (fallback). Missing PNGs flip the matching `_PRESENT` flag
to `false` so the firmware always compiles even before artwork lands.

Pack format matches `ps3::library::ThumbnailImage`:
  - row stride = (width + 1) / 2 bytes
  - even column -> high nibble, odd column -> low nibble
  - nibble value 0 = black, 0xF = white
This lets `blit_thumbnail()` render the icon without an extra blitter.

Runs both as a PlatformIO `extra_scripts = pre:` hook (SCons import is
optional) and as a standalone `python scripts/gen_icons.py` invocation.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Menu strip: 4 slots, each 135 x 110 px. Cap a bit under that.
MAX_MENU_ICON_W = 128
MAX_MENU_ICON_H = 100

# Toolbar strip: 60 px tall. Hard cap a bit under so the icon doesn't
# touch the new divider line at y=60.
MAX_TOOLBAR_ICON_W = 56
MAX_TOOLBAR_ICON_H = 56

# (png_stem, C++ symbol prefix). Menu order matches MenuButton enum.
MENU_ICONS = [
    ("folderup", "ICON_GOUP"),
    ("prev",     "ICON_PAGEPREV"),
    ("next",     "ICON_PAGENEXT"),
    ("lastbook", "ICON_LASTBOOK"),
]

TOOLBAR_ICONS = [
    ("sleep",      "ICON_TOOLBAR_SLEEP"),
    ("menu",       "ICON_TOOLBAR_MENU"),
    ("setting",    "ICON_TOOLBAR_SETTING"),
    ("full",       "ICON_TOOLBAR_FULL"),
    ("reload",     "ICON_TOOLBAR_RELOAD"),
    ("screenshot", "ICON_TOOLBAR_SCREENSHOT"),
    ("charge",     "ICON_TOOLBAR_CHARGE"),
]


def pack_image(img) -> bytes:
    """Convert an 8-bit grayscale PIL image (already at ICON_W x ICON_H)
    into the 4 bpp packed byte stream used by ThumbnailImage.
    """
    w, h = img.size
    bytes_per_row = (w + 1) // 2
    out = bytearray(bytes_per_row * h)
    px = img.load()
    for y in range(h):
        row_off = y * bytes_per_row
        for x in range(w):
            v = (px[x, y] >> 4) & 0x0F  # 0..255 -> 0..15
            byte_idx = row_off + (x >> 1)
            if (x & 1) == 0:
                out[byte_idx] |= v << 4   # even col -> high nibble
            else:
                out[byte_idx] |= v        # odd col  -> low nibble
    return bytes(out)


def emit_array(symbol: str, data: bytes) -> str:
    lines = [f"inline constexpr uint8_t {symbol}_DATA[] = {{"]
    chunk = []
    for i, b in enumerate(data):
        chunk.append(f"0x{b:02X},")
        if len(chunk) == 16:
            lines.append("    " + " ".join(chunk))
            chunk = []
    if chunk:
        lines.append("    " + " ".join(chunk))
    lines.append("};")
    return "\n".join(lines)


def emit_placeholder(symbol: str) -> str:
    return (f"inline constexpr uint8_t {symbol}_DATA[1] = {{0x00}};")


def render_header(entries: list[tuple[str, bool, int, int, bytes | None]]) -> str:
    """entries: [(symbol, present, w, h, packed_or_None), ...]"""
    out = []
    out.append("// AUTO-GENERATED by scripts/gen_icons.py — DO NOT EDIT.")
    out.append("// Source PNGs live under assets/icons/. Drop a file in")
    out.append("// that folder and rebuild to replace a slot. Each icon")
    out.append("// keeps its native PNG size so we never upscale into a")
    out.append("// blurry e-paper render.")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace ps3::library_view {")
    out.append("")
    for sym, present, w, h, packed in entries:
        out.append(f"inline constexpr bool {sym}_PRESENT = "
                   f"{'true' if present else 'false'};")
        out.append(f"inline constexpr int  {sym}_W = {w};")
        out.append(f"inline constexpr int  {sym}_H = {h};")
        if present and packed is not None:
            out.append(emit_array(sym, packed))
        else:
            out.append(emit_placeholder(sym))
        out.append("")
    out.append("}  // namespace ps3::library_view")
    return "\n".join(out) + "\n"


def process_set(icons: list, base_dir: Path,
                max_w: int, max_h: int, label: str, Image
                ) -> list[tuple[str, bool, int, int, bytes | None]]:
    """Convert one icon set (e.g. menu or toolbar) to header entries."""
    out: list[tuple[str, bool, int, int, bytes | None]] = []
    for stem, sym in icons:
        png = base_dir / f"{stem}.png"
        if Image is not None and png.exists():
            try:
                # Composite onto white before flattening to grayscale.
                # PIL's .convert("L") drops alpha — transparent pixels
                # whose underlying RGB is (0,0,0) (a common authoring
                # default) come out solid black, which on the e-paper
                # turns the whole icon into a black square.
                src = Image.open(png).convert("RGBA")
                bg  = Image.new("RGBA", src.size, (255, 255, 255, 255))
                img = Image.alpha_composite(bg, src).convert("L")
                w, h = img.size
                # Only resize if the artwork would overflow its strip
                # — never upscale, since LANCZOS upscaling on a 4 bpp
                # e-paper looks washed out.
                if w > max_w or h > max_h:
                    scale = min(max_w / w, max_h / h)
                    new_w = max(1, int(w * scale))
                    new_h = max(1, int(h * scale))
                    img = img.resize((new_w, new_h), Image.LANCZOS)
                    print(f"[gen_icons] {label}/{png.name}: "
                          f"{w}x{h} -> {new_w}x{new_h} (downscaled)")
                    w, h = new_w, new_h
                packed = pack_image(img)
                out.append((sym, True, w, h, packed))
                print(f"[gen_icons] embedded {label}/{png.name} "
                      f"({w}x{h}, {len(packed)} bytes)")
            except Exception as e:
                print(f"[gen_icons] WARN: failed to convert {png}: {e}",
                      file=sys.stderr)
                out.append((sym, False, 0, 0, None))
        else:
            out.append((sym, False, 0, 0, None))
    return out


def generate(project_dir: Path) -> int:
    assets_dir   = project_dir / "assets" / "icons"
    toolbar_dir  = assets_dir / "toolbar"
    out_path     = project_dir / "src" / "library" / "icons_data.hpp"


    have_any = (any((assets_dir / f"{s}.png").exists() for s, _ in MENU_ICONS)
                or any((toolbar_dir / f"{s}.png").exists() for s, _ in TOOLBAR_ICONS))

    Image = None
    if have_any:
        try:
            from PIL import Image as _Image
            Image = _Image
        except ImportError:
            print("[gen_icons] WARN: Pillow not installed in the active "
                  "Python; icons will fall back to text labels. "
                  "Run `pip install pillow` in the PlatformIO Python to "
                  "enable PNG embedding.", file=sys.stderr)
            Image = None

    entries: list[tuple[str, bool, int, int, bytes | None]] = []
    entries += process_set(MENU_ICONS,    assets_dir,
                           MAX_MENU_ICON_W,    MAX_MENU_ICON_H,
                           "menu", Image)
    entries += process_set(TOOLBAR_ICONS, toolbar_dir,
                           MAX_TOOLBAR_ICON_W, MAX_TOOLBAR_ICON_H,
                           "toolbar", Image)

    new_content = render_header(entries)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Skip the write if nothing changed, so PlatformIO doesn't think the
    # header was touched and rebuild every dependent .o.
    if out_path.exists():
        try:
            if out_path.read_text(encoding="utf-8") == new_content:
                return 0
        except OSError:
            pass

    out_path.write_text(new_content, encoding="utf-8")
    print(f"[gen_icons] wrote {out_path.relative_to(project_dir)}")
    return 0


# --- entry points -----------------------------------------------------

# PlatformIO's pre: hook injects an `env` SCons object. We don't need it,
# but importing is what tells us we're inside SCons. Standalone runs miss
# the `Import` builtin entirely, so guard it.
try:
    Import("env")  # type: ignore[name-defined]  # noqa: F821
    _PROJECT_DIR = Path(env["PROJECT_DIR"])  # noqa: F821
    generate(_PROJECT_DIR)
except NameError:
    if __name__ == "__main__":
        sys.exit(generate(Path(__file__).resolve().parents[1]))
